# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mdelarocha.github.io
title: Miguel Alejandro de la Rocha
email: delarochamiguelalex@gmail.com
author: Miguel A. de la Rocha
description: > # "Write an awesome description for your new site here. 
  Online Portfolio and Home of Miguel Alejandro de la Rocha for projects and presentations.
copyright: 'Copyright &copy; 2017 Miguel A. de la Rocha.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/migueldelaroch1
  - title: github
    url: https://github.com/mdelarocha
  - title: linkedin
    url: https://www.linkedin.com/in/miguel-de-la-rocha-699327140

